print("What's your favourite starter?")
starter = input()
print("what about mains?")
main_course = input()
print("ok... what about puddings?")
dessert = input()
print("and what do you like to drink?")
drink = input()
print("Alrighty, so your fave meal is " + starter + ", " + main_course + ", and " + dessert + " with a glass of " + drink)