table GdpPerCapita
	lineageTag: f64f6559-4d13-4cc5-8de4-6e2535492267

	column Code
		dataType: string
		isHidden
		lineageTag: 0c8b7a02-7d76-4b5e-aa3b-f403b9e5fe21
		summarizeBy: none
		sourceColumn: Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: aea70d43-d198-40c8-82b2-065b53f5e870
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'GDP per capita, PPP (constant 2021 international $)'
		dataType: double
		lineageTag: fae73d1f-a9aa-4ebd-abf8-f869f33aa3b2
		summarizeBy: sum
		sourceColumn: GDP per capita, PPP (constant 2021 international $)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition GdpPerCapita = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\gjeri\Desktop\PowerBI Projects\Emissions analysis\gdp-per-capita-worldbank\gdp-per-capita-worldbank.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Entity", type text}, {"Code", type text}, {"Year", Int64.Type}, {"GDP per capita, PPP (constant 2021 international $)", type number}, {"World regions according to OWID", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Entity", "World regions according to OWID"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Columns", each ([Code] <> null and [Code] <> "" and [Code] <> "OWID_WRL"))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

